server:
  port: 10010

spring:
  application:
    name: memory-mcp-server
  ai:
    mcp:
      server:
        name: memory-mcp-server
        version: 0.0.1
        type: SYNC
    alibaba:
      mcp:
        nacos:
          server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
          namespace: ${NACOS_NAMESPACE:public}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD:nacos}
          register:
            enabled: ${NACOS_REGISTER_ENABLED:true}

# Mem0 API 配置
mem0:
  api:
    url: ${MEM0_ADDRESS:https://api.mem0.ai}
    key: ${MEM0_API_KEY:-}
  client:
    timeout-seconds: 30
    max-retry-attempts: 3
